import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ServiceWorkerRegister from "@/components/ServiceWorkerRegister";
import InstallBanner from "@/components/InstallBanner";
import ProfileButton from "@/components/ProfileButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="tr">
      <head>
        <link rel="manifest" href="/manifest.webmanifest" />
        <meta name="theme-color" content="#16a34a" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        <div className="fixed bottom-2 left-2 z-40">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/api/qrcode?text=%2F" alt="QR" width={48} height={48} className="border rounded bg-white shadow opacity-80 hover:opacity-100 transition-opacity" />
        </div>
        <ProfileButton />
        <ServiceWorkerRegister />
        <InstallBanner />
      </body>
    </html>
  );
}
